### PR TITLE
feat: create workflow for tag creation

### PR DESCRIPTION
**Pull request by Tzal3x**
- [x] Create a `tag.yml` workflow that creates a tag given a commit and a tag name.

### CODE REVIEW

**Review by ebmifa — APPROVED** [review]

**Comment by giac-mysten** [comment]
do we have a use case for this workflow yet? what is triggering it?

**Comment by giac-mysten** [comment]
And regarding the use case? 
I think @ebmifa is looking into the binary workflow and versioning for sites (see [linear](https://linear.app/mysten-labs/issue/PRO-232/set-up-ci-workflows-for-site-builder-binaries-from-walrus-sites)). Probably good to wait for the outcome of that flow?

**Comment by Tzal3x** [comment]
> And regarding the use case? I think @ebmifa is looking into the binary workflow and versioning for sites (see [linear](https://linear.app/mysten-labs/issue/PRO-232/set-up-ci-workflows-for-site-builder-binaries-from-walrus-sites)). Probably good to wait for the outcome of that flow?

Sounds good, I just subscribed to the issue! Changing the PR to draft until further notice.

**Comment by mlegner** [comment]
I think this can be closed since #308 was merged.

**Pull request closed without merging**
